### 넘파이 배열
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자, 수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함
```bash
pip install numpy
```
numpy 패키지를 프로그램에서 사용하려면 import 해야 함
```python
import numpy
import numpy as np
```

In [1]:
import numpy as np

### 1차원 배열 만들기
넘파이의 `array` 함수를 사용하여 리스트를 `ndarray` 타입으로 변경 가능

In [3]:
ndarray_ = np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

In [4]:
type(ndarray_)

numpy.ndarray

In [6]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [7]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름

In [8]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [9]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
 numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원

In [12]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 때
numbers = list(range(10))
result = []
for number in numbers:
    result.append(number * 2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result =  2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [15]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [16]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [17]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [22]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 > 2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()`의 매개변수로 전달하면 2차원 배열을 생성할 수 있음

In [24]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
len(numpy_matrix)

3

In [26]:
numpy_matrix[0]

array([1, 2, 3])

In [27]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원 형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [28]:
three_d = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
`ndim` : 배열의 차원을 정수로 반환  
`shape` : 배열의 각 차원의 크기를 정수의 튜플로 반환  

In [29]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [30]:
numpy_three_d.ndim, numpy_three_d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 `배열변수[인덱스]` 의 형태로 사용함  
다차원 형태일 경우는 일반리스트와 다르게 `배열변수[인덱스, 인덱스, ...]` 의 형태로 사용함  
- 일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스, 인덱스]`

In [31]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [32]:
three_d[1][0][3]

16

In [33]:
# numpy 3차원 배열
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [34]:
numpy_three_d[1, 0, 3]

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]`와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 `,`를 써야하는 것에 주의 

In [35]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
numpy_matrix[0, :2]

array([1, 2])

In [40]:
numpy_matrix[:2, 0]

array([1, 4])

In [41]:
numpy_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [44]:
numpy_three_d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

#####  파이썬으로 다음 연산을 수행한다.
다음 행렬과 같은 행렬이 있다.

```
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</aside>

In [45]:

m = np.array([
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14]
    ])

In [57]:
# 1.
m[1, 2]

7

In [58]:
# 2.
m[2, 4]    # m[-1, -1]

14

In [59]:
# 3.
m[1, 1:3]

array([6, 7])

In [64]:
# 4.
m[1:, 2]

array([ 7, 12])

In [66]:
# 5.
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
**팬시 인덱싱(fancy indexing)** 이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱
`True`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [67]:
numpy_array = np.array([1, 2, 3, 4, 5, 6 , 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])